### ISSUE TITLE
Django integration

### ISSUE THREAD

**Issue by lmblanes** [HIT2GAP-EU-PROJECT/HIT2GAP-portal#2]
Der Pierre and Frederique
I tried many times to access the scr attribute of the parent i-frame using several strategies:

- accessing `window.parent.document.getElementById('module')` doesn't work as it gives this:
> SecurityError: Permission denied to access property "document" on cross-origin object

- I also tried with python requests and urrlib with no success

Is there any other recipe for a django based app to scrap that `?h2gtokenid`

**Comment by davidfrederique** [comment]
Hi,

If I understand well you want to get the `h2gtokenid` value from your module's url query paramerters, right?

If yes, you don't need to access to the parent document or even the window (anyway, for security reasons, the browser prevents you from doing so).
You just have to read the url of your page and extract the `h2gtokenid` query parameter.

Inside the HIT2GAP web portal I added a "Module Example" that shows some tricks, including the token retreiving from a module's url (you can view the code source through your browser).
![h2g-webportal_module-example](https://user-images.githubusercontent.com/18071905/57712848-9d108b80-7671-11e9-9ffb-d705cad8c204.png)

Here's 2 code samples:

1. A client-side code sample written in javascript:
```
// get full module url
var fullURL = document.location.href;
// get token
var urlObj = new URL(fullURL);
var h2gToken = urlObj.searchParams.get("h2gtokenid");
```

2. And a server-side python code sample, using Flask (which I assume is close to Django, as it serves web content written in python):
```
from flask import request

# get authentication token
h2gtoken = request.args.get('h2gtokenid')
```

You can found some more details in the [doc](https://github.com/HIT2GAP-EU-PROJECT/HIT2GAP-portal/blob/master/module-developers-doc.md#python-with-flask-and-requests-libraries).

Using Django framework, maybe the code in "Listing 2-9" of this [page](https://www.webforefront.com/django/accessurlparamstemplates.html) can help.

**Comment by lmblanes** [comment]
Hi Frederique
Tried many things around Listing 2-9 link 
I need to find another type of solution.

**Comment by lmblanes** [comment]
Hi David
Server side javascript does not work for me either.
Is there any other recipe?
